# Generated by Django 5.2.17 on 2026-09-02 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('country', models.CharField(default='China', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('ranking', models.PositiveIntegerField(blank=True, help_text='Optional overall ranking used for personal comparison.', null=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('degree_type', models.CharField(choices=[('BACHELOR', "Bachelor's"), ('MASTER', "Master's"), ('PHD', 'PhD')], max_length=20)),
                ('study_language', models.CharField(choices=[('ENGLISH', 'English'), ('CHINESE', 'Chinese'), ('BILINGUAL', 'Bilingual'), ('OTHER', 'Other')], default='ENGLISH', max_length=20)),
                ('duration', models.DecimalField(blank=True, decimal_places=1, help_text='Program duration in years.', max_digits=3, null=True)),
                ('tuition_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Annual tuition fee.', max_digits=12, null=True)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='universities.university')),
            ],
            options={
                'ordering': ['university__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('university', 'name', 'degree_type'), name='unique_program_per_university_degree')],
            },
        ),
    ]
