# Generated by Django 5.2.17 on 2026-09-02 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, help_text='For example: Professor, Associate Professor, Admissions Officer.', max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('research_area', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('NOT_CONTACTED', 'Not Contacted'), ('EMAIL_SENT', 'Email Sent'), ('RESPONDED', 'Responded'), ('FOLLOW_UP', 'Follow Up'), ('NO_RESPONSE', 'No Response'), ('NOT_INTERESTED', 'Not Interested'), ('POSITIVE', 'Positive Response')], default='NOT_CONTACTED', max_length=20)),
                ('last_contacted', models.DateField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, help_text='Optional application this contact is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='applications.application')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='universities.university')),
            ],
            options={
                'ordering': ['-updated_at', 'name'],
            },
        ),
    ]
