# Generated by Django 5.2.17 on 2026-09-02 13:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name that helps you identify this document.', max_length=255)),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('TRANSCRIPT', 'Transcript'), ('CV', 'CV / Resume'), ('STUDY_PLAN', 'Study Plan'), ('RECOMMENDATION', 'Recommendation Letter'), ('LANGUAGE_CERTIFICATE', 'Language Certificate'), ('ENROLLMENT_CERTIFICATE', 'Enrollment Certificate'), ('PHYSICAL_EXAMINATION', 'Physical Examination'), ('DIPLOMA', 'Diploma'), ('ID_PHOTO', 'ID Photo'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('file', models.FileField(upload_to='documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])])),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('TRANSCRIPT', 'Transcript'), ('CV', 'CV / Resume'), ('STUDY_PLAN', 'Study Plan'), ('RECOMMENDATION', 'Recommendation Letter'), ('LANGUAGE_CERTIFICATE', 'Language Certificate'), ('ENROLLMENT_CERTIFICATE', 'Enrollment Certificate'), ('PHYSICAL_EXAMINATION', 'Physical Examination'), ('DIPLOMA', 'Diploma'), ('ID_PHOTO', 'ID Photo'), ('OTHER', 'Other')], max_length=30)),
                ('required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('READY', 'Ready'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='NOT_STARTED', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_documents', to='applications.application')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_documents', to='documents.document')),
            ],
            options={
                'ordering': ['required', 'document_type'],
                'constraints': [models.UniqueConstraint(fields=('application', 'document', 'document_type'), name='unique_application_document')],
            },
        ),
    ]
