# Generated by Django 5.2.17 on 2026-09-02 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_application_unique_user_application_and_more'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='applicationdocument',
            name='unique_application_document',
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_documents', to='documents.document'),
        ),
        migrations.AddConstraint(
            model_name='applicationdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('document__isnull', False)), fields=('application', 'document', 'document_type'), name='unique_application_document'),
        ),
        migrations.AddConstraint(
            model_name='applicationdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('document__isnull', True)), fields=('application', 'document_type'), name='unique_application_document_requirement'),
        ),
    ]
