# Generated by Django 5.2.17 on 2026-09-02 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scholarships', '0001_initial'),
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RESEARCHING', 'Researching'), ('SHORTLISTED', 'Shortlisted'), ('PREPARING', 'Preparing'), ('APPLICATION_STARTED', 'Application Started'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('INTERVIEW', 'Interview'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='RESEARCHING', max_length=30)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('scholarship_deadline', models.DateField(blank=True, null=True)),
                ('portal_url', models.URLField(blank=True, help_text='Direct URL to the university application portal.')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='universities.program')),
                ('scholarship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='scholarships.scholarship')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='universities.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['application_deadline', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'university', 'program', 'scholarship'), name='unique_user_application')],
            },
        ),
    ]
