# Generated by Django 5.2.17 on 2026-09-02 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('scholarships', '0001_initial'),
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='application',
            name='unique_user_application',
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('scholarship__isnull', False)), fields=('user', 'university', 'program', 'scholarship'), name='unique_user_application_with_scholarship'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('scholarship__isnull', True)), fields=('user', 'university', 'program'), name='unique_user_application_without_scholarship'),
        ),
    ]
