# Generated by Django 5.2.17 on 2026-09-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(blank=True, help_text='Organization or institution providing the scholarship.', max_length=255)),
                ('scholarship_type', models.CharField(choices=[('GOVERNMENT', 'Government'), ('UNIVERSITY', 'University'), ('PROVINCIAL', 'Provincial'), ('PRIVATE', 'Private'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('coverage', models.TextField(blank=True, help_text='What expenses the scholarship covers.')),
                ('stipend', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly stipend, if applicable.', max_digits=10, null=True)),
                ('eligibility', models.TextField(blank=True)),
                ('application_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['deadline', 'name'],
            },
        ),
    ]
